brief-yoctoprojectqs: fix the allow root login command
The 'bitbake-config-build enable-fragment' command requires the full
namespace ('core/yocto/root-login-with-empty-password'). Passing only
'root-login-with-empty-password' fails.

ERROR: Fragment root-login-with-empty-password does not exist; use 'list-fragments' to see the full list.

Signed-off-by: El Mehdi YOUNES <elmehdi.younes@smile.fr>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>