brief-yoctoprojectqs: fix runqemu command
'runqemu qemux86-64' throws a MACHINE assignment conflict because the
machine is already set via the enabled fragment. Additionally, the
default compressed '.zst' image requires the 'snapshot' mode to boot.
Changed the command to 'runqemu snapshot'.

ERROR: A builtin fragment 'machine/qemux86-64' is used while MACHINE has already got an assignment.
ERROR: .zst images are only supported with snapshot mode. You can either use the "snapshot" option or use an uncompressed image

Signed-off-by: El Mehdi YOUNES <elmehdi.younes@smile.fr>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>